create table person(
    id number generated by default on null as identity primary key,
    nombre varchar2(50),
    apellido varchar2(50),
    email varchar2 (100),
    direccion varchar2(100)
);

create view view_Person as
select * from person;

create procedure GetPersonByID(
    p_id in number,
    cur out SYS_REFCURSOR
)IS
begin
    open cur for
    Select * from person where id = p_id;
end GetPersonByID;

create procedure addPerson(
    p_nombre in varchar2,
    p_apellido in varchar2,
    p_email in varchar2,
    p_direccion in VARCHAR2
)as
begin
    insert into person (nombre, apellido, email, direccion)
    values (p_nombre, p_apellido, p_email, p_direccion);
    commit;
end addPerson;

create procedure updatePerson(
    p_id in number,
    p_nombre in varchar2,
    p_apellido in varchar2,
    p_email in varchar2,
    p_direccion in VARCHAR2
)as
begin
    update person 
    set nombre = p_nombre,
        apellido = p_apellido,
        email = p_email,
        direccion = p_direccion
        where id = p_id;
    commit;
end updatePerson;

create procedure deletePerson(
    p_id in NUMBER
)as
begin
    delete from person where id = p_id;
    commit;
end deletePerson;

